code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension george-alisson.html-preview-vscode
code --install-extension mohd-akram.vscode-html-format
code --install-extension mohsen1.prettify-json
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension vscode-icons-team.vscode-icons
code --install-extension ZainChen.json
code --install-extension dbaeumer.vscode-eslint
